// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"

// code.cpp
cpp11::writable::integers_matrix turmite(int width, int height, int iter, int step_size);
extern "C" SEXP _turmite59_turmite(SEXP width, SEXP height, SEXP iter, SEXP step_size) {
  BEGIN_CPP11
    return cpp11::as_sexp(turmite(cpp11::as_cpp<cpp11::decay_t<int>>(width), cpp11::as_cpp<cpp11::decay_t<int>>(height), cpp11::as_cpp<cpp11::decay_t<int>>(iter), cpp11::as_cpp<cpp11::decay_t<int>>(step_size)));
  END_CPP11
}

extern "C" {
/* .Call calls */
extern SEXP _turmite59_turmite(SEXP, SEXP, SEXP, SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_turmite59_turmite", (DL_FUNC) &_turmite59_turmite, 4},
    {NULL, NULL, 0}
};
}

extern "C" void R_init_turmite59(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
}
