# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

turmite <- function(width, height, iter, step_size) {
    .Call('_turmite59_turmite', PACKAGE = 'turmite59', width, height, iter, step_size)
}

